# Automation example

- id: '0001'
  alias: Daily Irrigation Routine
  description: 08:00, 10:00, 12:30, 14:30, 16:30, 18:30
  trigger:
  - at: '08:00:00'
    platform: time
  - at: '10:00:00'
    platform: time
  - at: '12:30:00'
    platform: time
  - at: '14:30:00'
    platform: time
  - at: '16:30:00'
    platform: time
  - at: '18:30:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: script.zone_1_irrigation_for_10_min
    service: script.turn_on

- id: '0012'
  alias: Daily Irrigation Routine - Zone 2
  description: 07:00, 09:00, 11:30, 13:30, 15:30, 17:30, 19:30
  trigger:
  - at: '07:00:00'
    platform: time
  - at: '09:00:00'
    platform: time
  - at: '11:30:00'
    platform: time
  - at: '13:30:00'
    platform: time
  - at: '15:30:00'
    platform: time
  - at: '17:30:00'
    platform: time
  - at: '19:30:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: script.zone_2_irrigation_for_10_min
    service: script.turn_on

