
  - platform: mqtt
  name: "Relay/Solenoid 1"
  state_topic: "stat/relay01/RESULT"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/relay01/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/relay01/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Relay/Solenoid 2"
  state_topic: "stat/relay01/RESULT"
  value_template: "{{ value_json.POWER2 }}"
  command_topic: "cmnd/relay01/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/relay01/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
